version: '3'

services:
  backend:
    image: todobackend
    restart: always
    ports:
      -3001:3001

  frontend:
    image: todofrontend
    environment:
      - REACT_APP_API_HOST=backend
    depends_on:
      - backend
    restart: always
    ports:
      -3000:3000

  tests:
    image: todotests
    restart: always
    depends_on:
      - frontend
      - backend

